---
title: "About me"
description: 
site: distill::distill_website
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I’m Alex Oliver, chief data scientist at ES Partners / Evolving Strategies in Washington, D.C. I use the scientific method to change people’s opinions and behavior at scale for clients. I conduct survey and field experiments, use Bayesian statistics and machine learning, and primarily code in R.

I help Fortune 500 companies and political independent expenditure organizations. Since 2017, I’ve led over 50 research engagements that have impacted over 100 million consumers and voters.

My research has been presented to Capitol Hill and the White House. It has also been covered in *The New Yorker*, *Politico*, *Adweek*, and other media.

I’ve held lectureships at Brandeis University and Boston University. I’ve also taught courses on public opinion, voter behavior, and campaign strategy.

I have a Ph.D. in political science from Boston University. I also have an M.A. in economics from Tufts University and a B.A. in economics from Merrimack College.


