---
title: "Political case studies"
description: |
  Selected case studies from my recent political engagements
#author:
#  - name: Nora Jones 
#    url: https://example.com/norajones
#    affiliation: Spacely Sprockets
#    affiliation_url: https://example.com/spacelysprokets
#date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## A nonprofit cofounded by a former presidential candidate

### Situation

Stand Up Republican Foundation (SURF) was cofounded by former 2016 independent presidential candidate Evan McMullin and advocates for reforming election law and preventing foreign interference in elections. Stand Up Ideas planned to launch a digital media campaign to educate people about disinformation tactics and stop their spread. The organization wanted to know which video advertisement would lift people’s skepticism of “fake news” the most. 

### Intervention

We used the scientific method to measure the lift from three possible advertisements. Specifically, we designed and conducted randomized-controlled trial with a nationally representative sample of about 1,700 people. We found that the most effective of the three advertisements lifted skepticism by 21% among Donald Trump voters but by just 3% among Hillary Clinton voters.  

### Result

The organization’s campaign more effectively lifted people’s skepticism of fake news, especially for Trump voters. Further, we presented the study at the University of Cincinnati as part of its cybersecurity initiative.


## A Super PAC endorsed by a former Speaker of the House

### Situation

A Super PAC endorsed by a former Speaker of the House planned to spend over $400,000 to elect congressional, senatorial, and gubernatorial candidates in the swing states of Michigan and Pennsylvania. The organization wanted to know which political advertisements would lift voters' support for its candidates the most.

### Intervention

We used the scientific method to measure the lift from six possible advertisements. Specifically, we designed and conducted a randomized-controlled trial with a representative sample of about 4,600 registered voters in Michigan and Pennsylvania. We found that the most effective of the six advertisements lifted support by 23% overall. Further, we applied machine learning to our proprietary voter files to predict the individual lift for each of the 14.6 million voters in the two states.

### Result

The organization more effectively lifted overall support for its candidates in Michigan and Pennsylvania by only targeting advertisements to the top 1 million voters with the greatest predicted individual lift. Further, the organization's targeted advertising campaign led to the outperformance of its candidates on election day.


## A nonprofit developing a position on the FAMILY Act

### Situation

Independent Women’s Forum is an educational nonprofit that advocates for reforming the workplace through its Women at Work project. Independent Women’s Forum was developing a policy position on the Family and Medical Insurance Leave (FAMILY) Act, which would provide up to 12 weeks of partially paid leave to nearly all workers.  The organization wanted to know which features of a job would lift women’s preference for an employer the most.

### Intervention

We used the scientific method to measure the lift from 67 possible features of a job. Specifically, we designed and conducted a conjoint experiment with a nationally representative sample of about 1,000 women. We found that providing 12 weeks of partially paid leave lifted preference by 10%. But this is less than half the 22% lift from offering flexible schedules, reduced hours, and telecommuting.  

### Result

The organization took a position against the FAMILY Act and in favor of workplace flexibility options. The study was featured in *The Washington Post* and presented at the Workplace LEAD summit. Further, the organization’s leadership now has a data app for exploring women’s preferences across 165,888,000 combinations of job features — with different combinations of flexibility, vacation and sick days, paid leave, health insurance, and salary — as they develop future policy positions. 


## A behavioral science firm finding evidence of racial discrimination in plaintiff verdicts

### Situation

ES Partners was developing a prototype for a new legal analytics product called *JuryRank* for use by counsel during jury selection before civil trials. The firm wanted to rank every potential juror in a jurisdiction from most to least generous in awarding damages to plaintiffs in personal injury cases.  


### Intervention

We used the scientific method to estimate the level of damages under six case scenarios and 512 plaintiff profiles. Specifically, we designed and conducted a conjoint experiment with a representative sample of about 700 registered voters in New Jersey.  We then applied machine learning to our propretiary voter files to predict the individual damages awarded by each of the 5.3 million voters in the state. We found evidence of racial discrimination: white voters awarded black plaintiffs five percent less in damages than white plaintiffs, all else equal.

### Result

Civil litigation firms that subscribe to the *JuryRank* prototype leverage generosity rankings of potential jurors to obtain more favorable plaintiff verdicts and settlements for clients. Although many studies show racial discrimination against *black defendents in criminal cases*, this study is the first to show the same against *black plaintiffs in civil cases*. Further, the study was featured on *Real Clear Markets* and presented at the National Board of Trial Advocacy (NBTA) All Star Conference. 

